version: "3.9"

services:
  lenka-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lenka-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lenka.rule=Host(`apps.itsprobabl.com`) && PathPrefix(`/lenka`)"
      - "traefik.http.routers.lenka.entrypoints=web"
      - "traefik.http.services.lenka.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    networks:
      - traffic_net

networks:
  traffic_net:
    external: true
